/**
 * RASA Store — canonical category seed data.
 * RASA fashion category definitions.
 */
const rasaCategories = [
  {
    _id: "rasa-root",
    status: "show",
    name: { en: "Home" },
    id: "Root",
    parentName: "Home",
    description: { en: "RASA Store root category" },
  },
  // Main Categories
  {
    _id: "rasa-footwear",
    status: "show",
    name: { en: "Footwear" },
    parentId: "rasa-root",
    parentName: "Home",
    slug: "footwear",
    description: { en: "Premium footwear, sneakers, heels, slides" },
    icon: "",
  },
  {
    _id: "rasa-bags",
    status: "show",
    name: { en: "Bags" },
    parentId: "rasa-root",
    parentName: "Home",
    slug: "bags",
    description: { en: "Premium handbags, backpacks, crossbody bags, totes" },
    icon: "",
  },

  // Footwear Subcategories
  {
    _id: "footwear-sneakers",
    status: "show",
    name: { en: "Sneakers" },
    parentId: "rasa-footwear",
    parentName: "Footwear",
    slug: "footwear-sneakers",
    description: { en: "Sneakers collection" },
    icon: "",
  },
  {
    _id: "footwear-womensneakers",
    status: "show",
    name: { en: "Women's Sneakers" },
    parentId: "rasa-footwear",
    parentName: "Footwear",
    slug: "footwear-womens-sneakers",
    description: { en: "Women's Sneakers collection" },
    icon: "",
  },
  {
    _id: "footwear-heels",
    status: "show",
    name: { en: "Heels" },
    parentId: "rasa-footwear",
    parentName: "Footwear",
    slug: "footwear-heels",
    description: { en: "Premium heels collection" },
    icon: "",
  },
  {
    _id: "footwear-slides",
    status: "show",
    name: { en: "Slides & Slippers" },
    parentId: "rasa-footwear",
    parentName: "Footwear",
    slug: "footwear-slides-slippers",
    description: { en: "Slides & Slippers collection" },
    icon: "",
  },

  // Bag Subcategories
  {
    _id: "bags-tote",
    status: "show",
    name: { en: "Tote Bags" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-tote-bags",
    description: { en: "Tote Bags collection" },
    icon: "",
  },
  {
    _id: "bags-shoulder",
    status: "show",
    name: { en: "Shoulder Bags" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-shoulder-bags",
    description: { en: "Shoulder Bags collection" },
    icon: "",
  },
  {
    _id: "bags-crossbody",
    status: "show",
    name: { en: "Crossbody Bags" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-crossbody-bags",
    description: { en: "Crossbody Bags collection" },
    icon: "",
  },
  {
    _id: "bags-backpacks",
    status: "show",
    name: { en: "Backpacks" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-backpacks",
    description: { en: "Backpacks collection" },
    icon: "",
  },
  {
    _id: "bags-mini",
    status: "show",
    name: { en: "Mini Bags" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-mini-bags",
    description: { en: "Mini Bags collection" },
    icon: "",
  },
  {
    _id: "bags-clutches",
    status: "show",
    name: { en: "Clutches" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-clutches",
    description: { en: "Clutches collection" },
    icon: "",
  },
  {
    _id: "bags-travel",
    status: "show",
    name: { en: "Travel Bags" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-travel-bags",
    description: { en: "Travel Bags collection" },
    icon: "",
  },
  {
    _id: "bags-wallets",
    status: "show",
    name: { en: "Wallets & Accessories" },
    parentId: "rasa-bags",
    parentName: "Bags",
    slug: "bags-wallets-accessories",
    description: { en: "Wallets & Accessories collection" },
    icon: "",
  }
];

module.exports = rasaCategories;
